[target.aarch64-linux-android]
linker = "/opt/homebrew/share/android-commandlinetools/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang"
rustflags = ["-C", "link-arg=-llog"]
